export default useUser;
declare function useUser(): {
    loginUser: (username: any, password: any) => any;
    logoutUser: (redirectPath: any) => any;
    authenticationError: any;
    authenticationErrorMessage: any;
    userError: any;
    userErrorMessage: any;
    isAuthenticated: any;
    userIsLoading: any;
    user: any;
    userId: any;
    registerUser: (user: any, mappers: any) => any;
    registrationError: any;
    registrationIsLoading: any;
    registrationIsSuccess: any;
    userRegistration: any;
    passwordResetRequestIsLoading: any;
    passwordResetRequestIsSuccess: any;
    passwordResetRequestError: any;
    requestPasswordReset: (userEmailObject: any) => any;
    queryString: any;
    passwordResetIsLoading: any;
    passwordResetIsSuccess: any;
    passwordResetError: any;
    resetPassword: (resetPasswordObject: any) => any;
    changePasswordIsLoading: any;
    changePasswordIsSuccess: any;
    changePasswordError: any;
    changePassword: (userId: any, currentPassword: any, newPassword: any) => any;
};
