declare const _default: <Base extends {
    readonly currentHostname: null;
    readonly contentTypeId: null;
    readonly currentPath: string;
    readonly currentNode: {};
    readonly currentNodeAncestors: readonly never[];
    readonly currentProject: string;
    readonly entryID: null;
    readonly entry: null;
    readonly currentTreeId: null;
    readonly entryDepends: readonly never[];
    readonly error: undefined;
    readonly isError: boolean;
    readonly isLoading: boolean;
    readonly location: {};
    readonly mappedEntry: null;
    readonly nodeDepends: readonly never[];
    readonly notFound: boolean;
    readonly staticRoute: null;
    readonly statusCode: number;
}>(base?: Base | undefined, action: any) => any;
export default _default;
