import { Entry } from 'contensis-delivery-api/lib/models';
import { AppState } from "../../redux/appstate";
export declare const selectRouteEntry: (state: AppState) => Entry | null;
export declare const selectMappedEntry: (state: AppState) => Record<string, any> | null;
export declare const selectNodeDepends: (state: AppState) => string[];
export declare const selectCurrentHostname: (state: AppState) => null;
export declare const selectCurrentTreeID: (state: AppState) => null;
export declare const selectRouteEntryEntryId: (state: AppState) => string | null;
export declare const selectRouteEntryContentTypeId: (state: AppState) => string | null;
export declare const selectRouteEntryLanguage: (state: AppState) => string | null;
export declare const selectRouteEntrySlug: (state: AppState) => string | null;
export declare const selectRouteEntryID: (state: AppState) => string | null;
export declare const selectCurrentPath: (state: AppState) => string;
export declare const selectCurrentSearch: (state: AppState) => string;
export declare const selectCurrentHash: (state: AppState) => string;
export declare const selectQueryStringAsObject: (state: AppState) => any;
export declare const selectCurrentProject: (state: AppState) => string;
export declare const selectIsNotFound: (state: AppState) => boolean;
export declare const selectCurrentAncestors: (state: AppState) => import("contensis-delivery-api/lib/models").Node[];
export declare const selectCurrentSiblings: (state: AppState) => import("contensis-delivery-api/lib/models").Node[];
export declare const selectCurrentNode: (state: AppState) => import("contensis-delivery-api/lib/models").Node & {
    children: import("contensis-delivery-api/lib/models").Node[];
};
export declare const selectCurrentChildren: (state: any) => import("contensis-delivery-api/lib/models").Node[];
export declare const selectBreadcrumb: (state: AppState) => number;
export declare const selectRouteErrorMessage: (state: AppState) => any;
export declare const selectRouteIsError: (state: AppState) => boolean;
export declare const selectRouteLoading: (state: AppState) => boolean;
export declare const selectRouteStatusCode: (state: AppState) => number;
