const ROUTING_PREFIX = '@ROUTING/';
export const GET_ENTRY = `${ROUTING_PREFIX}_GET_ENTRY`;
export const SET_ENTRY = `${ROUTING_PREFIX}_SET_ENTRY`;
export const SET_NODE = `${ROUTING_PREFIX}_SET_NODE`;
export const SET_ANCESTORS = `${ROUTING_PREFIX}_SET_ANCESTORS`;
export const SET_SIBLINGS = `${ROUTING_PREFIX}_SET_SIBLINGS`;
export const SET_ENTRY_ID = `${ROUTING_PREFIX}_SET_ENTRY_ID`;
export const SET_API_METRICS = `${ROUTING_PREFIX}_SET_API_METRICS`;

export const SET_NAVIGATION_PATH = `${ROUTING_PREFIX}_SET_NAVIGATION_PATH`;

export const SET_TARGET_PROJECT = `${ROUTING_PREFIX}_SET_TARGET_PROJECT`;

export const SET_ROUTE = `${ROUTING_PREFIX}_SET_ROUTE`;

export const UPDATE_LOADING_STATE = `${ROUTING_PREFIX}_UPDATE_LOADING_STATE`;

/**
 * Non-redux "Live Preview" message channel action types
 */
export const LIVE_ENTRY_PREFIX = 'LIVE_ENTRY_';
export const LIVE_ENTRY_NAVIGATE = `${LIVE_ENTRY_PREFIX}NAVIGATE`;
export const LIVE_ENTRY_ROUTE_LOAD_OPTIONS = `${LIVE_ENTRY_PREFIX}ROUTE_LOAD_OPTIONS`;
export const LIVE_ENTRY_RESET = `${LIVE_ENTRY_PREFIX}RESET`;
export const LIVE_ENTRY_UPDATE = `${LIVE_ENTRY_PREFIX}UPDATE`;
