const FORM_PREFIX = '@FORM/';
export const SUBMIT_FORM = `${FORM_PREFIX}SUBMIT_FORM`;
export const FORM_SUBMITTING = `${FORM_PREFIX}FORM_SUBMITTING`;
export const SET_FORM_SUBMIT_ERROR = `${FORM_PREFIX}SET_FORM_SUBMIT_ERROR`;
export const SET_FORM_SUBMIT_SUCCESS = `${FORM_PREFIX}SET_FORM_SUBMIT_SUCCESS`;
export const RESET_FORM = `${FORM_PREFIX}RESET_FORM`;
export const SET_FORM = `${FORM_PREFIX}SET_FORM`;
export const UPDATE_FORM_DATA = `${FORM_PREFIX}UPDATE_FORM_DATA`;
