//  INITIALISE
export const NAVIGATION_INITIALISE_TREES = 'NAVIGATION_INITIALISE_TREES';
export const NAVIGATION_INITIALISE_TREES_ERROR =
  'NAVIGATION_INITIALISE_TREES_ERROR';

export const NAVIGATION_SET_WAYPOINT = 'NAVIGATION_SET_WAYPOINT';
// SETTING TREE
// ...ROOT
export const NAVIGATION_SET_TREE_ROOT = 'NAVIGATION_SET_TREE_ROOT';

// ...ENTRIES
export const NAVIGATION_SET_TREE_ENTRIES = 'NAVIGATION_SET_TREE_ENTRIES';
export const NAVIGATION_SET_TREE_ENTRIES_ERROR =
  'NAVIGATION_SET_TREE_ENTRIES_ERROR';
// ...SELECTIONS
export const NAVIGATION_SET_LAST_SELECTED_MENU_ITEM =
  'NAVIGATION_SET_LAST_SELECTED_MENU_ITEM';
export const NAVIGATION_CLEAR_MENU_ITEMS = 'NAVIGATION_CLEAR_MENU_ITEMS';
export const NAVIGATION_SET_IS_ACCORDIAN_MODE =
  'NAVIGATION_SET_IS_ACCORDIAN_MODE';
export const NAVIGATION_ADD_SELECTED_MENU_ITEM_FOR_ACCORDIAN =
  'NAVIGATION_ADD_SELECTED_MENU_ITEM_FOR_ACCORDIAN';
export const NAVIGATION_REMOVE_SELECTED_MENU_ITEM_FOR_ACCORDIAN =
  'NAVIGATION_REMOVE_SELECTED_MENU_ITEM_FOR_ACCORDIAN';
export const CLEAR_MENU_SELECTIONS = 'CLEAR_MENU_SELECTIONS';
export const CLEAR_MENU_SELECTIONS_FOR_TREE = 'CLEAR_MENU_SELECTIONS_FOR_TREE';

// PATH DICTIONARY
export const NAVIGATION_SET_PATH_DICTIONARY_ENTRY =
  'NAVIGATION_SET_PATH_DICTIONARY_ENTRY';
export const NAVIGATION_ENSURE_ENTRY_IN_PATH_DICTIONARY =
  'NAVIGATION_ENSURE_ENTRY_IN_PATH_DICTIONARY';
export const NAVIGATION_SET_PATH_DICTIONARY = 'NAVIGATION_SET_PATH_DICTIONARY';

// CONTENT TYPES ETC...
export const NavigationContentTypes = ['news', 'event', 'contentPage'];

// TODO - get this from cms site settings content type
export const MainNavigationSlug = 'main-navigation';

export const GET_NAVIGATION_TREE = 'GET_NAVIGATION_TREE';

export const ContentTypes = [
  'news',
  'event',
  'contentPage',
  'externalLink',
  'listing',
];
