const USER_PREFIX = '@USER/';
export const CHECK_USER_LOGGED_IN = `${USER_PREFIX}CHECK_USER_LOGGED_IN`;
export const SET_USER_DETAILS = `${USER_PREFIX}SET_USER_DETAILS`;
export const TOGGLE_USER_DETAILS_ARE_HIDDEN = `${USER_PREFIX}TOGGLE_USER_DETAILS_ARE_HIDDEN`;
export const SHOW_USER_DETAILS = `${USER_PREFIX}SHOW_USER_DETAILS`;
export const HIDE_USER_DETAILS = `${USER_PREFIX}HIDE_USER_DETAILS`;
export const SET_SHOW_USER_DETAILS = `${USER_PREFIX}SET_SHOW_USER_DETAILS`;
export const SIGN_OUT = `${USER_PREFIX}SIGN_OUT`;
