export const VALIDATE_USER: string;
export const SET_AUTHENTICATION_STATE: string;
export const LOGIN_USER: string;
export const LOGIN_SUCCESSFUL: string;
export const LOGIN_FAILED: string;
export const LOGOUT_USER: string;
export const REGISTER_USER: string;
export const REGISTER_USER_SUCCESS: string;
export const REGISTER_USER_FAILED: string;
