export const APP_INITIALISE = 'APP_INITIALISE';
export const APP_SET_SETTINGS = 'APP_SET_SETTINGS';
export const APP_SET_INITIALISED = 'APP_SET_INITIALISED';
export const APP_SET_INITIALISING = 'APP_SET_INITIALISING';
