export const GET_COUNTRIES = 'GET_COUNTRIES';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_COUNTRY = 'SET_COUNTRY';
export const SET_COUNTRY_REQUIREMENTS = 'SET_COUNTRY_REQUIREMENTS';
