export const LISTING_SET_NODE = 'LISTING_SET_NODE';

export const LISTING_SET_SEARCH_TERM = 'LISTING_SET_SEARCH_TERM';
export const LISTING_EXECUTE_SEARCH = 'LISTING_EXECUTE_SEARCH';
export const LISTING_SET_SEARCH_RESULTS = 'LISTING_SET_SEARCH_RESULTS';

export const LISTING_ENSURE_SEARCH_RESULTS = 'LISTING_ENSURE_SEARCH_RESULTS';
export const LISTING_ADD_RESULTS = 'LISTING_ADD_RESULTS';
export const LISTING_REPLACE_RESULTS = 'LISTING_REPLACE_RESULTS';
export const LISTING_SET_FILTER_DATE = 'LISTING_SET_FILTER_DATE';
export const LISTING_ADD_EVENT_TO_DATE_DICTIONARY =
  'LISTING_ADD_EVENT_TO_DATE_DICTIONARY';
export const LISTING_UPDATE_PAGE_INDEX = 'LISTING_UPDATE_PAGE_INDEX';
export const LISTING_SET_PAGE_COUNT = 'LISTING_SET_PAGE_COUNT';
export const LISTING_SET_CATEGORY_OPTION = 'LISTING_SET_CATEGORY_OPTION';
export const LISTING_SET_DATE_OPTION = 'LISTING_SET_DATE_OPTION';
