const ACTION_PREFIX = '@USER/';
export const SET_USER_LOADING = `${ACTION_PREFIX}SET_USER_LOADING`;
export const SET_AUTHENTICATION_STATE = `${ACTION_PREFIX}SET_AUTHENTICATION_STATE`;
export const LOGIN_USER = `${ACTION_PREFIX}LOGIN_USER`;
export const LOGIN_SUCCESSFUL = `${ACTION_PREFIX}LOGIN_SUCCESSFUL`;
export const LOGIN_FAILED = `${ACTION_PREFIX}LOGIN_FAILED`;
export const LOGOUT_USER = `${ACTION_PREFIX}LOGOUT_USER`;
export const CREATE_USER_ACCOUNT = `${ACTION_PREFIX}CREATE_USER_ACCOUNT`;
